### ISSUE TITLE
Add regen-config subcommand

### ISSUE THREAD

**Issue by kirtangajjar** [EasyEngine/site-type-wp#65] opened 2018-10-01 10:44 UTC
When doing rsync or moving some site to ee, often you accidentally replace `wp-config.php` and then you have to manually create it by looking at credentials from `ee site info`.

This can be automated by a single command `regen-config`.

**Comment by mrrobot47** [comment] 2018-11-29 07:10
Closing as duplicate of https://github.com/EasyEngine/feature-requests/issues/11

**Closed by mrrobot47** 2018-11-29 07:10 UTC
Labels: good first issue
